  
name: 'Development Pipeline'

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'

env:
  FORTRAN_COMPILER: gfortran-10
  NUM_PROCS: 8

# runs-on: ${{ matrix.os }}
# strategy:
#   matrix:
#     os: [macOS-10.14, ubuntu-18.04]

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Setup
        run: cmake -E make_directory ${{runner.workspace}}/build
      - name: Configure
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake \
            -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/install \
            -DCMAKE_Fortran_COMPILER:STRING=${{env.FORTRAN_COMPILER}} \
            -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo \
            -DBUILD_TESTING:BOOL=ON \
            -DCODECOV=ON \
            ${GITHUB_WORKSPACE}
      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --target newtonraphson_utest -- -j ${{env.NUM_PROCS}}
      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: |
          ./sqrt_fortran 4
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          # files: ./coverage1.xml,./coverage2.xml # optional
          # flags: unittests # optional
          # name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
